/**
 * satrlar royxatidagi har bir matnning bosh joylarini olib tas
 * Auto-generated by GitHub Auto Repo Manager PRO v2.0
 */

const http = require('http');

const config = {
  port: process.env.PORT || 3000,
  name: 'satrlar-royxatidagi-har-bir-matnning-bosh-joylarini-olib-tas',
  version: '1.0.0',
};

class Application {
  constructor(config) {
    this.config = config;
    this.server = null;
    this.routes = new Map();
    this.middleware = [];
  }

  use(fn) {
    this.middleware.push(fn);
    return this;
  }

  route(method, path, handler) {
    const key = `${method.toUpperCase()}:${path}`;
    this.routes.set(key, handler);
    return this;
  }

  async handleRequest(req, res) {
    const key = `${req.method}:${req.url}`;
    const handler = this.routes.get(key);

    // Run middleware
    for (const mw of this.middleware) {
      await mw(req, res);
    }

    if (handler) {
      const result = await handler(req, res);
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(result));
    } else {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Not Found' }));
    }
  }

  start() {
    this.server = http.createServer((req, res) => this.handleRequest(req, res));
    this.server.listen(this.config.port, () => {
      console.log(`🚀 ${this.config.name} v${this.config.version} running on port ${this.config.port}`);
    });
    return this;
  }
}

// Initialize
const app = new Application(config);

// Middleware
app.use((req, res) => {
  req.startTime = Date.now();
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
});

// Routes
app.route('GET', '/', () => ({
  name: config.name,
  version: config.version,
  status: 'healthy',
  uptime: process.uptime(),
  timestamp: new Date().toISOString(),
}));

app.route('GET', '/health', () => ({
  status: 'ok',
  memory: process.memoryUsage(),
}));

// Start
app.start();

module.exports = { Application };
